import { NextResponse } from "next/server";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export async function GET() {
  try {
    const session = await getServerSession(authOptions);

    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Get user statistics
    const [totalImages, favoriteImages, recentImages, providerStats] =
      await Promise.all([
        // Total images generated by user
        prisma.generatedImage.count({
          where: { userId: session.user.id },
        }),

        // Favorite images count
        prisma.generatedImage.count({
          where: {
            userId: session.user.id,
            isFavorite: true,
          },
        }),

        // Recent images (last 7 days)
        prisma.generatedImage.count({
          where: {
            userId: session.user.id,
            createdAt: {
              gte: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
            },
          },
        }),

        // Images by provider
        prisma.generatedImage.groupBy({
          by: ["provider"],
          where: { userId: session.user.id },
          _count: {
            id: true,
          },
        }),
      ]);

    // Get recent images for dashboard preview
    const recentImagesList = await prisma.generatedImage.findMany({
      where: { userId: session.user.id },
      select: {
        id: true,
        prompt: true,
        provider: true,
        createdAt: true,
        // S3 storage fields
        s3Url: true,
        s3Key: true,
        s3Bucket: true,
        // Legacy storage fields
        imageUrl: true,
        imagePath: true,
      },
      orderBy: { createdAt: "desc" },
      take: 6,
    });

    return NextResponse.json({
      totalImages,
      favoriteImages,
      recentImages,
      providerStats: providerStats.reduce(
        (
          acc: Record<string, number>,
          stat: { provider: string; _count: { id: number } }
        ) => {
          acc[stat.provider] = stat._count.id;
          return acc;
        },
        {} as Record<string, number>
      ),
      recentImagesList,
    });
  } catch (error) {
    console.error("Dashboard stats error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
